# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Task2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import Lab1


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 610)
        MainWindow.setStyleSheet("background-color: rgb(246, 246, 246);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(230, 255, 220);")
        self.centralwidget.setObjectName("centralwidget")
        self.btn_calculate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calculate.setGeometry(QtCore.QRect(160, 540, 300, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_calculate.setFont(font)
        self.btn_calculate.setStyleSheet("background-color: rgb(197, 255, 176);")
        self.btn_calculate.setObjectName("btn_calculate")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(20, 40, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_name.setFont(font)
        self.label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name.setObjectName("label_name")
        self.label_games_list = QtWidgets.QLabel(self.centralwidget)
        self.label_games_list.setGeometry(QtCore.QRect(40, 240, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_games_list.setFont(font)
        self.label_games_list.setAlignment(QtCore.Qt.AlignCenter)
        self.label_games_list.setObjectName("label_games_list")
        self.label_winner = QtWidgets.QLabel(self.centralwidget)
        self.label_winner.setGeometry(QtCore.QRect(140, 420, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_winner.setFont(font)
        self.label_winner.setAlignment(QtCore.Qt.AlignCenter)
        self.label_winner.setObjectName("label_winner")
        self.line_edit_name = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit_name.setGeometry(QtCore.QRect(20, 80, 400, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_name.setFont(font)
        self.line_edit_name.setStyleSheet("background-color: rgb(197, 255, 176);")
        self.line_edit_name.setText("")
        self.line_edit_name.setObjectName("line_edit_name")
        self.plain_text_edit_games_list = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plain_text_edit_games_list.setGeometry(QtCore.QRect(20, 240, 560, 120))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plain_text_edit_games_list.setFont(font)
        self.plain_text_edit_games_list.setStyleSheet("background-color: rgb(197, 255, 176);")
        self.plain_text_edit_games_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plain_text_edit_games_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plain_text_edit_games_list.setPlainText("")
        self.plain_text_edit_games_list.setObjectName("plain_text_edit_games_list")
        self.plain_text_edit_winner = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plain_text_edit_winner.setGeometry(QtCore.QRect(60, 460, 480, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plain_text_edit_winner.setFont(font)
        self.plain_text_edit_winner.setStyleSheet("background-color: rgb(197, 255, 176);")
        self.plain_text_edit_winner.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plain_text_edit_winner.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plain_text_edit_winner.setPlainText("")
        self.plain_text_edit_winner.setObjectName("plain_text_edit_winner")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(80, 0, 440, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.line_edit_sum = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit_sum.setGeometry(QtCore.QRect(460, 80, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_sum.setFont(font)
        self.line_edit_sum.setStyleSheet("background-color: rgb(197, 255, 176);")
        self.line_edit_sum.setText("")
        self.line_edit_sum.setObjectName("line_edit_sum")
        self.label_sum = QtWidgets.QLabel(self.centralwidget)
        self.label_sum.setGeometry(QtCore.QRect(460, 40, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_sum.setFont(font)
        self.label_sum.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_sum.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sum.setObjectName("label_sum")
        self.btn_donate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_donate.setGeometry(QtCore.QRect(160, 160, 300, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_donate.setFont(font)
        self.btn_donate.setStyleSheet("background-color: rgb(197, 255, 176);")
        self.btn_donate.setObjectName("btn_donate")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

        self.games_list = {}

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Задание 1"))
        self.btn_calculate.setText(_translate("MainWindow", "Сгенерировать"))
        self.label_name.setText(_translate("MainWindow", "Название игры"))
        self.label_games_list.setText(_translate("MainWindow", "Список игр"))
        self.label_winner.setText(_translate("MainWindow", "Игра-победитель"))
        self.label_title.setText(_translate("MainWindow", "3. \"Колесо фортуны\" для стримера"))
        self.label_sum.setText(_translate("MainWindow", "Сумма"))
        self.btn_donate.setText(_translate("MainWindow", "Пожертвовать"))


    def add_functions(self):
        self.btn_calculate.clicked.connect(lambda: self.calculate_result())
        self.btn_donate.clicked.connect(lambda: self.donate())


    def calculate_result(self):   
        if self.games_list: 
            game_name = Lab1.fortune_wheel_for_streamer(self.games_list)
            self.plain_text_edit_winner.setPlainText(game_name)


    def donate(self):
        name = self.line_edit_name.text()
        sum = self.line_edit_sum.text()

        if len(name) == 0:
                error = QMessageBox()
                error.setWindowTitle('Неверный ввод')
                error.setText('Заполните поле "Название игры"')
                error.setIcon(QMessageBox.Information)
                error.exec_()
                return

        try:
            sum = float(sum)
            if 0 >= sum:
                raise ValueError
            if ( len(str(sum)) - 1 - str(sum).find('.')) > 2:
                error = QMessageBox()
                error.setWindowTitle('Неверный ввод')
                error.setText('max 2 знака после .')
                error.setIcon(QMessageBox.Information)
                error.exec_()
                return
        except ValueError:
            self.line_edit_sum.setText('')
            error = QMessageBox()
            error.setWindowTitle('Неверный ввод')
            error.setText('Cумма должна быть >0')
            error.setIcon(QMessageBox.Information)
            error.exec_()
            return

        if name in self.games_list.keys():
            self.games_list[name] += sum
            self.plain_text_edit_games_list.setPlainText('')
            for key in self.games_list:
                self.plain_text_edit_games_list.insertPlainText(
                    key + '    ' + str(self.games_list[key]) + '\n')
        else:
            self.games_list[name] = sum
            self.plain_text_edit_games_list.insertPlainText(name + '    ' + str(sum) + '\n')
        
        self.line_edit_name.setText('')
        self.line_edit_sum.setText('')



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
