# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Task1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import SimpleRandomEvent as SRE


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 350)
        MainWindow.setStyleSheet("background-color: rgb(246, 246, 246);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(230, 255, 220);")
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(0, 5, 600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.btn_calculate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calculate.setGeometry(QtCore.QRect(160, 260, 300, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_calculate.setFont(font)
        self.btn_calculate.setStyleSheet("background-color: rgb(197, 255, 176);")
        self.btn_calculate.setObjectName("btn_calculate")
        self.label_task = QtWidgets.QLabel(self.centralwidget)
        self.label_task.setGeometry(QtCore.QRect(18, 60, 600, 60))
        self.label_task.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_task.setWordWrap(True)
        self.label_task.setObjectName("label_task")
        self.line_edit_p = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit_p.setGeometry(QtCore.QRect(20, 180, 140, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_p.setFont(font)
        self.line_edit_p.setStyleSheet("background-color: rgb(197, 255, 176);")
        self.line_edit_p.setText("")
        self.line_edit_p.setObjectName("line_edit_p")
        self.label_p = QtWidgets.QLabel(self.centralwidget)
        self.label_p.setGeometry(QtCore.QRect(10, 140, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_p.setFont(font)
        self.label_p.setAlignment(QtCore.Qt.AlignCenter)
        self.label_p.setObjectName("label_p")
        self.label_result_title = QtWidgets.QLabel(self.centralwidget)
        self.label_result_title.setGeometry(QtCore.QRect(240, 140, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_result_title.setFont(font)
        self.label_result_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_result_title.setObjectName("label_result_title")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(230, 180, 140, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_result.setFont(font)
        self.label_result.setStyleSheet("background-color: rgb(197, 255, 176);")
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.label_p_10_6_res = QtWidgets.QLabel(self.centralwidget)
        self.label_p_10_6_res.setGeometry(QtCore.QRect(440, 180, 140, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_p_10_6_res.setFont(font)
        self.label_p_10_6_res.setStyleSheet("background-color: rgb(197, 255, 176);")
        self.label_p_10_6_res.setText("")
        self.label_p_10_6_res.setObjectName("label_p_10_6_res")
        self.label_p_10_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_p_10_6.setGeometry(QtCore.QRect(440, 140, 130, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_p_10_6.setFont(font)
        self.label_p_10_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_p_10_6.setObjectName("label_p_10_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Задание 1"))
        self.label_title.setText(_translate("MainWindow", "Имитация простого случайного события"))
        self.btn_calculate.setText(_translate("MainWindow", "Сгенерировать"))
        self.label_task.setText(_translate("MainWindow", "    На вход генератора подается вероятность р простого случайного события.\n"
"В результате работы генератор должен вернуть с заданной вероятностью\n"
"True, если событие произошло, и False, если событие не произошло."))
        self.label_p.setText(_translate("MainWindow", "0 \u2264 p \u2264 1"))
        self.label_result_title.setText(_translate("MainWindow", "Результат"))
        self.label_p_10_6.setText(_translate("MainWindow", "p при 10\u2076"))

    def add_functions(self):
        self.btn_calculate.clicked.connect(lambda: self.calculate_result())

    def calculate_result(self):
        p = self.line_edit_p.text()

        try:
            p = float(p)
            if not 0 <= p <= 1:
                raise ValueError
        except ValueError:
            self.line_edit_p.setText('')
            error = QMessageBox()
            error.setWindowTitle('Неверный ввод')
            error.setText('p - число в [0, 1]')
            error.setIcon(QMessageBox.Information)
            error.exec_()
            return

        self.label_p_10_6_res.setText('')
        self.label_result.setText('')
        
        result, p_10_6 = SRE.simulation_simple_random_event(p=p)
        self.label_p_10_6_res.setText('{:.6f}'.format(p_10_6))
        self.label_result.setText('  ' + str(result))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
