# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Task1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

import CommonUI
from ConsoleMains.DSVmain import * 
import Generator.FormDSV as FormDSV
import StatisticalStudy.DSV.StStudyDSV as StStudyDSV
import StatisticalStudy.HypothesisTesting as HT


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1224, 604)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_FR = QtWidgets.QLabel(self.centralwidget)
        self.label_FR.setGeometry(QtCore.QRect(60, 40, 222, 32))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_FR.setFont(font)
        self.label_FR.setObjectName("label_FR")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(350, 0, 682, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.chooseP = QtWidgets.QComboBox(self.centralwidget)
        self.chooseP.setEnabled(True)
        self.chooseP.setGeometry(QtCore.QRect(20, 70, 242, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chooseP.setFont(font)
        self.chooseP.setObjectName("chooseP")
        self.chooseP.addItem("")
        self.chooseP.addItem("")
        self.chooseP.addItem("")
        self.label_N = QtWidgets.QLabel(self.centralwidget)
        self.label_N.setGeometry(QtCore.QRect(20, 120, 25, 40))
        self.label_N.setObjectName("label_N")
        self.N_count = QtWidgets.QLineEdit(self.centralwidget)
        self.N_count.setGeometry(QtCore.QRect(55, 120, 80, 40))
        self.N_count.setObjectName("N_count")
        self.label_M = QtWidgets.QLabel(self.centralwidget)
        self.label_M.setGeometry(QtCore.QRect(150, 120, 25, 40))
        self.label_M.setObjectName("label_M")
        self.M_count = QtWidgets.QLineEdit(self.centralwidget)
        self.M_count.setGeometry(QtCore.QRect(182, 120, 80, 40))
        self.M_count.setObjectName("M_count")
        self.label_FR_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_FR_4.setGeometry(QtCore.QRect(50, 159, 202, 32))
        self.label_FR_4.setObjectName("label_FR_4")
        self.label_FR_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_FR_5.setGeometry(QtCore.QRect(40, 195, 42, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_FR_5.setFont(font)
        self.label_FR_5.setObjectName("label_FR_5")
        self.Y_count = QtWidgets.QLineEdit(self.centralwidget)
        self.Y_count.setGeometry(QtCore.QRect(80, 195, 182, 40))
        self.Y_count.setObjectName("Y_count")
        self.generate_btn = QtWidgets.QPushButton(self.centralwidget)
        self.generate_btn.setGeometry(QtCore.QRect(20, 250, 242, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.generate_btn.setFont(font)
        self.generate_btn.setObjectName("generate_btn")
        self.indep_cond_denc_btn = QtWidgets.QPushButton(self.centralwidget)
        self.indep_cond_denc_btn.setGeometry(QtCore.QRect(20, 330, 242, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.indep_cond_denc_btn.setFont(font)
        self.indep_cond_denc_btn.setObjectName("indep_cond_denc_btn")
        self.histograms_btn = QtWidgets.QPushButton(self.centralwidget)
        self.histograms_btn.setGeometry(QtCore.QRect(20, 410, 242, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.histograms_btn.setFont(font)
        self.histograms_btn.setObjectName("histograms_btn")
        self.estimates_btn = QtWidgets.QPushButton(self.centralwidget)
        self.estimates_btn.setGeometry(QtCore.QRect(20, 490, 242, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.estimates_btn.setFont(font)
        self.estimates_btn.setObjectName("estimates_btn")
        self.results = QtWidgets.QTextEdit(self.centralwidget)
        self.results.setGeometry(QtCore.QRect(286, 80, 922, 502))
        self.results.setObjectName("results")
        self.label_FR_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_FR_6.setGeometry(QtCore.QRect(740, 40, 222, 32))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_FR_6.setFont(font)
        self.label_FR_6.setObjectName("label_FR_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_FR.setText(_translate("MainWindow", "Матрица вероятностей"))
        self.label_title.setText(_translate("MainWindow", "Имитация системы дискретных СВ X и Y"))
        self.label_N.setText(_translate("MainWindow", "N ="))
        self.label_M.setText(_translate("MainWindow", "M ="))
        self.label_FR_4.setText(_translate("MainWindow", "Кол-во элементовтов X(Y)"))
        self.label_FR_5.setText(_translate("MainWindow", "n ="))
        self.generate_btn.setText(_translate("MainWindow", "Сгенерировать СВ"))
        self.histograms_btn.setText(_translate("MainWindow", "Гистограммы Х, Y"))
        self.estimates_btn.setText(_translate("MainWindow", "Характеристики\n (M, D, R)"))
        self.indep_cond_denc_btn.setText(_translate("MainWindow", "Независимость X, Y\nУсловные плотности"))
        self.results.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_FR_6.setText(_translate("MainWindow", "Результаты"))
        self.chooseP.setItemText(0, _translate("MainWindow", "Независимые Х и Y"))
        self.chooseP.setItemText(1, _translate("MainWindow", "Зависимые Х и Y"))
        self.chooseP.setItemText(2, _translate("MainWindow", "Случайная геннерация P"))

    def add_functions(self):
        self.generate_btn.clicked.connect(lambda: self.generate_SV())
        self.indep_cond_denc_btn.clicked.connect(lambda: self.st_study_indep_cond_denc())
        self.histograms_btn.clicked.connect(lambda: self.st_study_histograms())
        self.estimates_btn.clicked.connect(lambda: self.st_study_estimates())

    glob_x, glob_y = [], []
    glob_P = [[]]


    def generate_SV(self):
        ''' Генерация СВ '''
        self.results.clear()

        P_type = self.chooseP.currentIndex()

        if P_type == 0:
            P =  [[0.01, 0.04, 0.02, 0.03],
                            [0.04, 0.16, 0.08, 0.12],
                            [0.02, 0.08, 0.04, 0.06],
                            [0.03, 0.12, 0.06, 0.09]]
        elif P_type == 1:
            P =  [[0.1, 0.05, 0.1],
                             [0.1, 0.1, 0.05],
                             [0.05, 0.05, 0.1],
                             [0.05, 0.2, 0.05]]
        elif P_type == 2:
            N, M = self.N_count.text(), self.M_count.text()
            try:
                N = int(N)
                if N < 2:
                    raise ValueError
            except ValueError:
                self.N_count.setText('')
                error = QMessageBox()
                error.setWindowTitle('Неверный ввод')
                error.setText('N - целое число > 1')
                error.setIcon(QMessageBox.Information)
                error.exec_()
                return
            try:
                M = int(M)
                if M < 2:
                    raise ValueError
            except ValueError:
                self.M_count.setText('')
                error = QMessageBox()
                error.setWindowTitle('Неверный ввод')
                error.setText('M - целое число > 1')
                error.setIcon(QMessageBox.Information)
                error.exec_()
                return

            P = FormDSV.generate_2DSV_matrix(N, M)

        count = self.Y_count.text()

        try:
            count = int(count)
            if count < 10:
                raise ValueError
        except ValueError:
            self.Y_count.setText('')
            error = QMessageBox()
            error.setWindowTitle('Неверный ввод')
            error.setText('n - целое число > 10')
            error.setIcon(QMessageBox.Information)
            error.exec_()
            return

        #  формированиe двумерной ДСВ
        self.glob_x, self.glob_y = FormDSV.form_values(P, count=count)

        self.results.append('Матрица вероятностей P:')
        N, M = len(P), len(P[0])
        for i in range(N):
            str_res = ''
            for j in range(M):
                str_res += '{:.4f}   '.format(P[i][j])
            self.results.append(str_res)

        self.glob_P = P



    def st_study_indep_cond_denc(self):
        ''' Статистическое исследование. Проверка СВ Х и У на независимость. Условные плотности распределения '''
        if self.glob_x == [] or self.glob_y == [] or self.glob_P == [[]]:
            error = QMessageBox()
            error.setWindowTitle('Предупреждение')
            error.setText('Точки не сгенерированны.\nНажмите "Сгенерировать"')
            error.setIcon(QMessageBox.Information)
            error.exec_()
            return

        P = self.glob_P

        self.results.clear()

        # oдномерные законы распределения
        Px, Py = FormDSV.find_one_dimensional_2DSV(P)
        self.results.append('Одномерные законы распределения:')
        self.results.append('p(xi|y) = {:}     sum = {:}\np(yi|x) = {:}     sum = {:}'
                            .format(Px, sum(Px), Py, sum(Py)))

        # проверка на независимость
        independent = StStudyDSV.is_independent(P, Px, Py)
        str_res = 'Да' if independent else 'Нет'
        self.results.append('\nСВ Х и У независимы? ' + str_res)

        # условные плотности распределения
        Pxy, Pyx = StStudyDSV.conditional_dencity(P, Px, Py)
        self.results.append('\nУсловные законы распределения:')
        self.results.append('p(xi|y) = ')
        N, M = len(P), len(P[0])
        for i in range(N):
            str_res = ''
            for j in range(M):
                str_res += '{:.4f}   '.format(Pxy[i][j])
            self.results.append(str_res)
        self.results.append('sum = {:}\n\np(yi|x) = '.format(sum(Px)))
        for i in range(N):
            str_res = ''
            for j in range(M):
                str_res += '{:.4f}   '.format(Pyx[i][j])
            self.results.append(str_res)
        self.results.append('sum = {:}\n'.format(sum(Py)))

        


    def st_study_histograms(self):
        ''' Статистическое исследование. Гистограммы составляющих НСВ - СВ Х и У 2D и 3D '''
        if self.glob_x == [] or self.glob_y == []:
            error = QMessageBox()
            error.setWindowTitle('Предупреждение')
            error.setText('Точки не сгенерированны.\nНажмите "Сгенерировать"')
            error.setIcon(QMessageBox.Information)
            error.exec_()
            return

        P = self.glob_P
        self.results.clear()

        Px, Py = FormDSV.find_one_dimensional_2DSV(P)
        Pxy, Pyx = StStudyDSV.conditional_dencity(P, Px, Py)

        # гистограммы составляющих двумерной ДСВ
        StStudyDSV.plot_histograms(self.glob_x, self.glob_y, Px, Pyx)

        # гистограммa распределения двумерной ДСВ (3D-график)
        StStudyDSV.plot_histogram_3D(self.glob_x, self.glob_y, P)



    def st_study_estimates(self):
        ''' Статистическое исследование. Теоретические, точечные и интервальные значения МО, дисперсии, корреляции '''
        if self.glob_x == [] or self.glob_y == []:
            error = QMessageBox()
            error.setWindowTitle('Предупреждение')
            error.setText('Точки не сгенерированны.\nНажмите "Сгенерировать"')
            error.setIcon(QMessageBox.Information)
            error.exec_()
            return

        P = self.glob_P
        self.results.clear()

        Px, Py = FormDSV.find_one_dimensional_2DSV(P)
        Pxy, Pyx = StStudyDSV.conditional_dencity(P, Px, Py)

        # теоретические, точечные и интервальные значения характеристик ДСВ (МО, дисперсия, корреляция)
        Mx, Dx, My, Dy, Rxy, Mx_t, Dx_t, My_t, Dy_t, Rxy_t = StStudyDSV.point_estimates(
            self.glob_x, self.glob_y, P, Pyx)

        pe_params = Mx, Dx, Mx_t, Dx_t, My, Dy, My_t, Dy_t, Rxy, Rxy_t
        CommonUI.print_point_estimates(pe_params, self.results)

        ie_params_x, ie_params_y, ie_params_r =  StStudyDSV.interval_estimates(
            self.glob_x, self.glob_y, Mx, Mx_t, Dx, Dx_t, My, My_t, Dy, Dy_t, Rxy, Rxy_t)

        CommonUI.print_interval_estimates(ie_params_x, pe_params[0:4], self.results, sv_name='X')
        CommonUI.print_interval_estimates(ie_params_y, pe_params[4:8], self.results, sv_name='Y')
        CommonUI.print_interval_estimates_R(ie_params_r, pe_params[8:], self.results)

        # проверка гипотез. Проверка гипотезы о равенстве статистических средних значений и дисперсий
        n = len(self.glob_x)
        x_params_M, y_params_M, x_params_D, y_params_D = HT.test(
            Mx, Mx_t, My, My_t, Dx, Dx_t, Dy, Dy_t, Rxy, Rxy_t, n)

        cursor = self.results.textCursor()
        cursor.insertText("\n\n         Проверка гипотезы о соответствии полученных M и D теоретическим\n")
        cursor.insertText("Проверка МО для СВ Х")
        print_criterion_results(x_params_M, self.results)
        cursor.insertText("\nПроверка МО для СВ Y")
        print_criterion_results(y_params_M, self.results)
        cursor.insertText("\nПроверка дисперсии для СВ Х")
        print_criterion_results(x_params_D, self.results)
        cursor.insertText("\nПроверка дисперсии для СВ Y")
        print_criterion_results(y_params_D, self.results)


def print_criterion_results(crit_params, textedit):
    ''' Вывод результата проверки гипотезы о  соответствии  полученных  M и D теоретическим '''
    cursor = textedit.textCursor()

    a, X, X_tb = crit_params
    headers, rows = CommonUI.print_criterion_table(a, X, X_tb)
    CommonUI.print_table_to_textedit(headers, rows, textedit)




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())



